version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: final_assignment
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: dibimbing
      MB_DB_HOST: host.docker.internal
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
networks:
  metanet1:
    driver: bridge

